In [2]:
import numpy as np
raw_codes = np.load("/homes/al4624/Documents/YuE_finetune/finetune_testing_dataset/noised_inst_codes/078303.Instrumental.noised.npy")
print(raw_codes)
raw_codes = raw_codes[0:1, :]
print(raw_codes)

[[ 130  102  791 ...  257   67 1001]
 [ 238  238  760 ...  431  135  949]
 [ 731  116  673 ...  706  404 1009]
 ...
 [ 244  691  258 ...  957  998  761]
 [ 168  454  669 ...  320  353  793]
 [ 531  112  528 ...  795 1018  162]]
[[ 130  102  791 ...  257   67 1001]]
